#!/usr/bin/env Rscript
# ==============================================================================
# 03_generate_data_readme.R -- write data/compiled/README_data.md from the archive
# itself plus code/zenodo/column_dictionary.csv.
#
# The README used to be maintained by hand and drifted from the archive twice in
# one session: it documented seven datasets that had been moved or dropped and
# omitted four that had been added. Generating it means the dictionary is the
# only thing to maintain, and the check below means a new column cannot ship
# undocumented.
#
#   Rscript code/zenodo/03_generate_data_readme.R          # write the README
#   Rscript code/zenodo/03_generate_data_readme.R --check  # report gaps, write nothing
#
# Exits non-zero if any column in the archive has no dictionary entry, or if the
# dictionary describes a dataset or column that is no longer in the archive.
# ==============================================================================
suppressMessages({library(dplyr); library(readr)})

ARCHIVE <- "data/compiled"
DICT    <- "code/zenodo/column_dictionary.csv"
OUT     <- file.path(ARCHIVE, "README_data.md")
check_only <- "--check" %in% commandArgs(trailingOnly = TRUE)

stopifnot(dir.exists(ARCHIVE), file.exists(DICT))
D <- read_csv(DICT, show_col_types = FALSE) %>%
  mutate(across(everything(), ~ ifelse(is.na(.x), "", as.character(.x))))

files <- sort(basename(list.files(ARCHIVE, "[.]csv$")))

# Datasets whose columns are sample identifiers rather than fixed fields; a
# per-column dictionary is meaningless for these, so they are described once.
WIDE <- c(otu_table_16S.csv =
            "One row per ASV, one column per sample. Values are read counts. Column names are sample IDs matching `sample_id` in sample_metadata_16S.csv; the first column is the ASV identifier used in taxonomy_key_16S.csv.")

# ---- gather the archive's actual shape --------------------------------------
shape <- lapply(files, function(f) {
  p <- file.path(ARCHIVE, f)
  h <- read.csv(p, nrows = 1, check.names = FALSE, stringsAsFactors = FALSE)
  n <- tryCatch(length(count.fields(p, sep = ",", quote = "\"")) - 1L,
                error = function(e) NA_integer_)
  list(file = f, cols = names(h), nrow = n,
       types = vapply(h, function(x) class(x)[1], character(1)))
})
names(shape) <- files

# ---- coverage check ---------------------------------------------------------
missing <- list(); orphan <- list()
for (f in files) {
  if (f %in% names(WIDE)) next
  have <- D$column[D$dataset == f]
  want <- shape[[f]]$cols
  m <- setdiff(want, have); o <- setdiff(have, want)
  if (length(m)) missing[[f]] <- m
  if (length(o)) orphan[[f]]  <- o
}
dead <- setdiff(unique(D$dataset), c(files, names(WIDE)))

cat("=== archive coverage ===\n")
cat(sprintf("  datasets in archive: %d | dictionary entries: %d\n", length(files), nrow(D)))
if (length(missing)) {
  cat("\n  COLUMNS WITH NO DICTIONARY ENTRY:\n")
  for (f in names(missing))
    cat(sprintf("    %-34s %s\n", f, paste(head(missing[[f]], 12), collapse = ", ")))
}
if (length(orphan)) {
  cat("\n  dictionary entries for columns no longer present:\n")
  for (f in names(orphan))
    cat(sprintf("    %-34s %s\n", f, paste(head(orphan[[f]], 12), collapse = ", ")))
}
if (length(dead)) cat("\n  dictionary describes datasets not in the archive:\n    ",
                      paste(dead, collapse = ", "), "\n")

nbad <- length(missing) + length(orphan) + length(dead)
if (check_only) {
  cat(sprintf("\n%s\n", if (nbad) "GAPS FOUND" else "dictionary and archive agree"))
  quit(status = if (nbad) 1L else 0L)
}
if (length(missing))
  stop("refusing to write a README with undocumented columns; add them to ", DICT,
       " or run with --check to list them", call. = FALSE)

# ---- emit -------------------------------------------------------------------
fmt_n <- function(x) formatC(x, big.mark = ",", format = "d")
L <- c(
"# Compiled Datasets",
"",
"Analysis-ready datasets from the Yale-Myers Forest tree methane project. Each CSV",
"is self-contained, with documented columns and units, intended for reanalysis and",
"meta-analysis.",
"",
"**Citation**: Gewirtzman, J. (2026). jgewirtzman/tree-methanogens: Tree Microbiomes",
"and Methane Exchange in Upland Forests — Code & Data. Zenodo.",
"https://doi.org/10.5281/zenodo.18779715",
"",
"**License**: CC-BY 4.0",
"",
"**Scope**: one table per kind of observation, each row kept and flagged rather than",
"deleted. Results computed from them (stand budget, scaling grid, model skill, the",
"isotope summary and the paper's tables) are in `results/`. Raw instrument files are",
"in `data/raw/` and intermediate products in `data/processed/`.",
"",
"*This file is generated by `code/zenodo/03_generate_data_readme.R` from",
"`code/zenodo/column_dictionary.csv`. Edit the dictionary, not this file. Every",
"cleaning rule is listed in `code/DATA_HYGIENE.md` in the code repository.*",
"",
"---",
"",
"## How the datasets relate",
"",
sprintf("**CH4 flux.** `flux_stem.csv` (%s deployments) and `flux_soil.csv` (%s) hold every", fmt_n(shape[["flux_stem.csv"]]$nrow), fmt_n(shape[["flux_soil.csv"]]$nrow)),
"chamber deployment once, from all campaigns, with the goFlux fit diagnostics, the",
"minimum detectable flux and detection status, and the flags: `qc_pass` (procedural",
"failure only), `dead_stem`, `untagged_rescue`, `in_rf_training` and `exclusion_reason`.",
"Filter on `in_rf_training` to reproduce the random forests; use all rows to describe",
"the measurements. `unique_id` joins to the raw goFlux results.",
"",
"**Trees.** `tree_properties.csv` is a per-tree wide view (one row per tree): internal",
"gas, wood density and moisture by radial position, soil horizons, and copies of the",
"flux and gene values held at measurement level in `flux_stem.csv` and",
"`ddpcr_gene_abundances.csv`.",
"",
"**Internal gas and isotopes.** `internal_gas.csv` holds one row per gas sample;",
"`isotopes.csv` holds every Picarro run with `in_whole_tree_set` marking the samples",
"analysed and `exclusion_reason` saying why the others are not.",
"",
sprintf("**Inventory.** `forest_inventory_stems.csv` is the whole stand (%s stems): the 2018 and", fmt_n(shape[["forest_inventory_stems.csv"]]$nrow)),
"2019 censuses and a by-tag survey, one row per stem, with `in_stand` marking the stems",
"inside the censused stand (the budget basis). Census-only attributes are in the",
"`census_*` columns and are NA for by-tag stems.",
"",
"**16S.** `otu_table_16S.csv` holds read counts, `taxonomy_key_16S.csv` the",
"assignment for each ASV, and `sample_metadata_16S.csv` the sample attributes,",
"including the sequencing facility's qPCR 16S and ITS copy numbers.",
"",
"---",
"")
for (i in seq_along(files)) {
  f <- files[i]; sh <- shape[[f]]
  L <- c(L, sprintf("## %d. `%s`", i, f), "",
         sprintf("%s rows x %d columns.", fmt_n(sh$nrow), length(sh$cols)), "")
  if (f %in% names(WIDE)) {
    L <- c(L, WIDE[[f]], "", "---", "")
    next
  }
  dd <- D[D$dataset == f, ]
  desc <- unique(dd$dataset_description)
  L <- c(L, "| Column | Type | Unit | Description |",
            "|--------|------|------|-------------|")
  for (cn in sh$cols) {
    r <- dd[dd$column == cn, ][1, ]
    L <- c(L, sprintf("| %s | %s | %s | %s |", cn, r$type, r$unit, r$description))
  }
  L <- c(L, "", "---", "")
}
RES <- sort(list.files(file.path(ARCHIVE, "results"), "[.]csv$"))
if (length(RES)) L <- c(L, "## Results (`results/`)", "",
  "Copied from the pipeline's outputs without recomputation; each is the source of the",
  "numbers the paper quotes. Generated by `code/zenodo/02_compile_results.R`.", "",
  paste0("- `", RES, "`"), "")
writeLines(L, OUT)
cat(sprintf("\nwrote %s (%d datasets, %d documented columns)\n",
            OUT, length(files), sum(vapply(shape, function(s) length(s$cols), 1L))))
