#!/usr/bin/env Rscript
# ==============================================================================
# rev_write_parameter_record.R
# ------------------------------------------------------------------------------
# Regenerates the HEADLINE block of code/revision/notes/scaling_parameters.md from
# the canonical outputs, replacing everything between the two marker lines.
#
# WHY. scaling_parameters.md is the document the handoff tells the next session to
# read FIRST, and its section 0 asserts:
#
#     "Every number below is read from outputs/ and regenerated by
#      code/run_all.R. Nothing here is typed by hand."
#
# That was false. The block was hand-frozen and drifted through four rounds of
# changes -- it was still reporting a 4.91 mg band and a -445.4 soil term while the
# outputs said 4.378 and -422.157. A file that claims machine provenance while
# carrying stale literals is worse than one that admits it is prose, because it is
# the one document a reader is told not to check.
#
# This script makes the claim true. It writes ONLY between the markers, so the
# hand-written sections (the sourcing, the caveats, the reasoning) are untouched.
#
# Note the file lives under code/revision/notes/, which is gitignored and private.
# Nothing here writes to the public tree.
#
# Usage:  Rscript code/09_tables_stats/rev_write_parameter_record.R
# ==============================================================================
source("code/lib/rev_geometry.R")

MD    <- "code/revision/notes/scaling_parameters.md"
BEGIN <- "<!-- BEGIN GENERATED: headline -- rev_write_parameter_record.R -->"
END   <- "<!-- END GENERATED -->"

rd <- function(p) if (file.exists(p)) utils::read.csv(p, stringsAsFactors = FALSE) else NULL
B  <- rd("outputs/data/canonical_budget.csv")
G  <- rd("outputs/data/scaling_full_grid.csv")
H  <- rd("outputs/data/scaling_headline.csv")
W  <- rd("outputs/data/wai_bottomup.csv")
GC <- rd("outputs/data/rf_grouped_cv.csv")
CS <- rd("outputs/data/rf_calibration_sensitivity.csv")
if (is.null(B) || is.null(G) || is.null(H))
  stop("missing canonical outputs -- run the CORE chain first")
v <- function(q) { x <- B$value[B$quantity == q]; if (!length(x)) stop("no ", q); x[1] }
gcv <- function(m) if (is.null(GC)) NA_real_ else GC$grouped_r2[GC$model == m][1]
gsd <- function(m) if (is.null(GC)) NA_real_ else GC$grouped_r2_sd[GC$model == m][1]

nonup <- G[G$flux != "linear_bounded_median", ]
L <- c(
BEGIN,
"",
sprintf("*Generated %s by `rev_write_parameter_record.R`. Do not edit by hand -- edits",
        format(Sys.Date(), "%Y-%m-%d")),
"between the markers are overwritten. Every value is read from `outputs/`.*",
"",
"## 0. HEADLINE RESULT",
"",
sprintf("Grid = %d combinations = %d flux forms x %d WAI x %d branch x %d bole.",
        nrow(G), length(unique(G$flux)), length(unique(G$WAI)),
        length(unique(G$branch)), length(unique(G$bole))),
"",
"| quantity | value |",
"|---|---|",
sprintf("| Measured band (0-2 m) | **%.3f mg CH4 m-2 yr-1** -- invariant across all %d |",
        v("tree_measured_mg_m2_yr"), nrow(G)),
if (!is.null(CS)) sprintf("| -- calibration sensitivity | %.3f - %.3f mg |",
        min(CS$total_mg), max(CS$total_mg)) else NULL,
sprintf("| -- as %% of soil uptake | **%.3f%%** |", v("tree_pct_of_soil")),
sprintf("| Soil | **%.3f mg CH4 m-2 yr-1** (per m2 GROUND, x soil fraction %.5f) |",
        v("soil_mg_m2_yr"), v("soil_area_fraction")),
sprintf("| Net measured | **%.3f** |", v("net_measured_mg_m2_yr")),
sprintf("| Whole surface, all %d | **%.1f to %.1f mg** |", nrow(G), min(G$total_mg), max(G$total_mg)),
sprintf("| -- excluding the uptake form (%d) | %.1f to %.1f mg |",
        nrow(nonup), min(nonup$total_mg), max(nonup$total_mg)),
sprintf("| -- as %% of soil uptake | %.1f%% to %.1f%% |", min(G$pct_of_soil), max(G$pct_of_soil)),
sprintf("| Net budget across the grid | %.1f to %.1f -- a sink in **%d of %d** |",
        min(G$net_mg), max(G$net_mg), sum(G$net_mg < 0), nrow(G)),
sprintf("| Named scenario | **%.2f mg**, %.2f%% of soil, %.0f%% extrapolated |",
        H$total_mg[1], H$pct_of_soil[1], H$pct_extrapolated[1]),
sprintf("| TreeRF | OOB %.4f, grouped-CV-by-tree **%.4f** (sd %.4f) |",
        v("tree_r2_oob"), gcv("TreeRF"), gsd("TreeRF")),
sprintf("| SoilRF | OOB %.4f, grouped-CV-by-collar **%.4f** (sd %.4f) |",
        v("soil_r2_oob"), gcv("SoilRF"), gsd("SoilRF")),
"",
"### Stand",
"",
sprintf("Censused stand **%d m2** (%.2f ha) = %d x %d nominal minus %d m2 uncensused.",
        v("stand_area_m2"), v("stand_area_m2")/1e4, PLOT_SIDE_M, PLOT_SIDE_M, v("notch_area_m2")),
sprintf("**%d stems** (%d unlocated, retained). Basal area %.2f m2 = %.2f m2 ha-1.",
        v("n_stems"), v("n_stems_unlocated"), v("basal_area_m2"), v("basal_area_m2_ha")),
sprintf("Stem area 0-2 m **%.1f m2**, index **%.5f**. Soil area %.1f m2.",
        v("stem_area_0_2m_m2"), v("stem_area_index"), v("soil_area_m2")),
"",
"### The named scenario, defined once",
"",
sprintf("`%s` flux | %s | `%s` branch | `%s` bole.", H$flux[1], H$WAI[1], H$branch[1], H$bole[1]),
"**THE RANGE IS THE RESULT.** This is one cell of the grid, not an estimate; see",
"`manuscript/OPEN_DECISIONS.md` decision D.",
"",
"### WAI axis",
"",
if (!is.null(W)) sprintf("Bottom-up **%.2f / %.2f / %.2f** over %d stems and %.0f m2 (`wai_bottomup.csv`);",
        W$wai[1], W$wai[2], W$wai[3], W$n_stems[1], W$stand_area_m2[1]) else NULL,
"literature bounds 1.50 (W&W Brookhaven) and 3.07 (Gauci 2024). Note 3.07 now sits",
"INSIDE the bottom-up range, so it is no longer an upper bound -- see decision E.",
"",
"### Which assumption moves the answer most",
"",
"| assumption | levels | median total | spread |",
"|---|---|---|---|")
for (ax in c("flux","WAI","branch","bole")) {
  med <- tapply(G$total_mg, G[[ax]], median)
  L <- c(L, sprintf("| %s | %d | %.1f to %.1f | **%.1f mg** |",
                    ax, length(med), min(med), max(med), max(med) - min(med)))
}
L <- c(L, "", END)

txt <- readLines(MD, warn = FALSE)
b <- which(txt == BEGIN); e <- which(txt == END)
if (length(b) == 1 && length(e) == 1 && e > b) {
  txt <- c(txt[seq_len(b - 1)], L, txt[(e + 1):length(txt)])
  cat("replaced the generated block\n")
} else {
  hdr <- grep("^## 0\\. HEADLINE RESULT", txt)
  nxt <- grep("^## 1\\.", txt)
  if (length(hdr) == 1 && length(nxt) >= 1 && nxt[1] > hdr) {
    txt <- c(txt[seq_len(hdr - 1)], L, "", txt[nxt[1]:length(txt)])
    cat("markers absent -- replaced section 0 and inserted them\n")
  } else stop("cannot locate section 0 in ", MD)
}
writeLines(txt, MD)
cat(sprintf("  Written: %s (%d lines generated)\n", MD, length(L)))
