# ==============================================================================
# Generate All Figures
# ==============================================================================
# Purpose: Master runner script that regenerates all publication figures
#   (main + supplementary) from the project root directory.
#
# Usage: Rscript code/generate_all_figures.R
#   (must be run from the project root directory)
#
# Outputs:
#   - outputs/figures/original/main/fig1-fig9
#   - outputs/figures/original/supplementary/figS1-figS15
# ==============================================================================

cat("============================================================\n")
cat("Generating all publication figures\n")
cat("============================================================\n\n")

# Verify we're in the project root
if (!file.exists("data/processed/integrated/merged_tree_dataset_final.csv")) {
  stop("ERROR: Must run from project root directory.\n",
       "  Expected: data/processed/integrated/merged_tree_dataset_final.csv\n",
       "  Usage: Rscript code/generate_all_figures.R")
}

# Track results
results <- data.frame(
  script = character(),
  figures = character(),
  status = character(),
  time_sec = numeric(),
  error_msg = character(),
  stringsAsFactors = FALSE
)

run_figure_script <- function(script_path, figure_names) {
  cat(sprintf("--- %-65s ", script_path))
  start_time <- Sys.time()

  tryCatch({
    source(script_path, local = new.env(parent = globalenv()))
    elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
    cat(sprintf("\u2713 (%.1fs)\n", elapsed))
    results <<- rbind(results, data.frame(
      script = script_path, figures = figure_names,
      status = "PASS", time_sec = round(elapsed, 1),
      error_msg = "", stringsAsFactors = FALSE
    ))
  }, error = function(e) {
    elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
    cat(sprintf("\u2717 (%.1fs)\n", elapsed))
    cat(sprintf("    ERROR: %s\n", conditionMessage(e)))
    results <<- rbind(results, data.frame(
      script = script_path, figures = figure_names,
      status = "FAIL", time_sec = round(elapsed, 1),
      error_msg = conditionMessage(e), stringsAsFactors = FALSE
    ))
  })
}

# ==============================================================================
# MAIN FIGURES
# ==============================================================================
cat("=== Main figures ===\n\n")

run_figure_script("code/archive/superseded_2026-10-01/08_figures/06_soil_tree_timeseries.R",          "fig1")
run_figure_script("code/09_tables_stats/01_height_effects.R", "fig2")
run_figure_script("code/08_figures/04_variance_partition.R",             "fig3")
run_figure_script("code/archive/superseded_2026-10-01/08_figures/util_combined_plot.R",                  "fig4")
run_figure_script("code/archive/superseded_2026-10-01/08_figures/08c_combined_methane_cycling_composition.R", "fig5")
run_figure_script("code/08_figures/figS11-13_picrust-heatmaps.R",       "fig6")
run_figure_script("code/archive/superseded_2026-10-01/08_figures/09_felled_oak_profiles.R",            "fig7")

# fig8: sources its own upstream dependencies (02 + 03) via internal source() calls
run_figure_script("code/08_figures/fig08_radial-species.R",   "fig8")


# ==============================================================================
# SUPPLEMENTARY FIGURES
# ==============================================================================
cat("\n=== Supplementary figures ===\n\n")

run_figure_script("code/08_figures/figS09_taxonomy-pmoa.R",         "S2")
run_figure_script("code/08_figures/figS10_faprotax.R",             "S3")
# S4, S5 already generated by fig6 script (12b_picrust_pathway_heatmap.R)
run_figure_script("code/08_figures/figS14_taxonomy-mcra.R",         "S6")
run_figure_script("code/08_figures/figS15-16_internal-gas.R",             "S7, S8")
run_figure_script("code/archive/superseded_2026-10-01/08_figures/11a_isotope_d13ch4_single.R",         "S9")
run_figure_script("code/archive/superseded_2026-10-01/07_molecular/methanotrophs/03_pmoa_mmox_analysis.R", "S10")

# S11, S14 generated by 02_scale_dependent (already sourced as part of fig8)

run_figure_script("code/archive/superseded_2026-10-01/08_figures/10_black_oak_methanome_heatmap.R",    "S12")
run_figure_script("code/08_figures/figS22_radial-sections.R",          "S13")
run_figure_script("code/archive/superseded_2026-10-01/08_figures/08_rf_publication_plots.R",           "S15")

# S1 runs LAST because the maps pipeline loads the raster package which masks
# dplyr::select. Sources its own upstream dependencies (01_forestgeo + 02_spatial).
run_figure_script("code/08_figures/figS01_moisture-overlay.R",               "S1")


# ==============================================================================
# SUMMARY
# ==============================================================================
cat("\n============================================================\n")
cat("SUMMARY\n")
cat("============================================================\n\n")

n_pass <- sum(results$status == "PASS")
n_fail <- sum(results$status == "FAIL")
n_total <- nrow(results)
total_time <- sum(results$time_sec)

cat(sprintf("Total scripts: %d  |  Passed: %d  |  Failed: %d  |  Time: %.0fs\n\n",
            n_total, n_pass, n_fail, total_time))

# Print results table
for (i in seq_len(nrow(results))) {
  icon <- if (results$status[i] == "PASS") "\u2713" else "\u2717"
  cat(sprintf("  %s %-12s %s\n", icon, results$figures[i],
              basename(results$script[i])))
}

if (n_fail > 0) {
  cat("\n--- FAILURES ---\n")
  failed <- results[results$status == "FAIL", ]
  for (i in seq_len(nrow(failed))) {
    cat(sprintf("  %s: %s\n", failed$script[i], failed$error_msg[i]))
  }
}

cat("\n============================================================\n")
